### ISSUE TITLE
Using WaitForPipeDrain is not cross-platform way

### ISSUE THREAD

**Issue by rstm-sf** [daveaglick/MsBuildPipeLogger#3]
Hello!

Using `WaitForPipeDrain` is not cross-platform way. It's [only windows](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.pipestream.waitforpipedrain?view=net-5.0)

https://github.com/daveaglick/MsBuildPipeLogger/blob/39819e5c40635112e3c5f4ad041c6ba6e3bde864/src/MsBuildPipeLogger.Logger/PipeWriter.cs#L75

**Comment by daveaglick** [comment]
So I've apparently forgotten about this for [checks watch] almost a year. It would be easy enough to surround the call with an OS check, but I'm a little confused why this hasn't blown up in practice since it's used in [Buildalyzer](https://github.com/daveaglick/Buildalyzer) and that gets tested cross-platform. Is it possible this is a no-op on non-Windows platforms? And any idea what the non-Windows wait for drain equivalent should be?

**Comment by xoofx** [comment]
>  Is it possible this is a no-op on non-Windows platforms? 

Nope, it's a throw. 

https://github.com/dotnet/runtime/blob/ba4eae0b96f2a569050bd315b0b51609993e237c/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L354

> I'm a little confused why this hasn't blown up in practice

Because it is in a try/catch, so likely, the `_pipeStream.Dispose();` is never called on non-Windows platforms.

https://github.com/daveaglick/MsBuildPipeLogger/blob/39819e5c40635112e3c5f4ad041c6ba6e3bde864/src/MsBuildPipeLogger.Logger/PipeWriter.cs#L71-L80

**Comment by xoofx** [comment]
Fixed by PR #7

**Comment by daveaglick** [comment]
> Because it is in a try/catch, so likely, the _pipeStream.Dispose(); is never called on non-Windows platforms.

Oh, duh 🤦‍♂️. And not getting to the dispose could have unpleasant side-effects, so glad this got reported and fixed. Thanks both!
